// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TradingPilot.EntityFrameworkCore;
using Volo.Abp.EntityFrameworkCore;

#nullable disable

namespace TradingPilot.Migrations
{
    [DbContext(typeof(TradingPilotDbContext))]
    [Migration("20260316023505_AddSymbolTables")]
    partial class AddSymbolTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.PostgreSql)
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TradingPilot.Symbols.Symbol", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<string>("Exchange")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsMarginable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsShortable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsWatched")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateOnly?>("ListDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Sector")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte>("SecurityType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)1);

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)1);

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("WebullExchangeId")
                        .HasColumnType("integer");

                    b.Property<long>("WebullTickerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IsWatched")
                        .HasDatabaseName("IX_Symbols_IsWatched")
                        .HasFilter("\"IsWatched\" = true");

                    b.HasIndex("Ticker")
                        .IsUnique()
                        .HasDatabaseName("IX_Symbols_Ticker");

                    b.HasIndex("WebullTickerId")
                        .IsUnique()
                        .HasDatabaseName("IX_Symbols_WebullTickerId");

                    b.ToTable("Symbols", (string)null);
                });

            modelBuilder.Entity("TradingPilot.Symbols.SymbolBar", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ChangeRatio")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)");

                    b.Property<decimal>("Close")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("High")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("Low")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("Open")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<Guid>("SymbolId")
                        .HasColumnType("uuid");

                    b.Property<byte>("Timeframe")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Vwap")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp", "Timeframe")
                        .HasDatabaseName("IX_SymbolBars_Timestamp_Timeframe");

                    b.HasIndex("SymbolId", "Timeframe", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("IX_SymbolBars_SymbolId_Timeframe_Timestamp");

                    b.ToTable("SymbolBars", (string)null);
                });

            modelBuilder.Entity("TradingPilot.Symbols.SymbolBookSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string>("AskPrices")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<string>("AskSizes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<string>("BidPrices")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<string>("BidSizes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Depth")
                        .HasColumnType("integer");

                    b.Property<decimal>("Imbalance")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)");

                    b.Property<decimal>("MidPrice")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("Spread")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<Guid>("SymbolId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_SymbolBookSnapshots_Timestamp");

                    b.HasIndex("SymbolId", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("IX_SymbolBookSnapshots_SymbolId_Timestamp");

                    b.ToTable("SymbolBookSnapshots", (string)null);
                });

            modelBuilder.Entity("TradingPilot.Symbols.SymbolBar", b =>
                {
                    b.HasOne("TradingPilot.Symbols.Symbol", null)
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TradingPilot.Symbols.SymbolBookSnapshot", b =>
                {
                    b.HasOne("TradingPilot.Symbols.Symbol", null)
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
