// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TradingPilot.EntityFrameworkCore;
using Volo.Abp.EntityFrameworkCore;

#nullable disable

namespace TradingPilot.Migrations
{
    [DbContext(typeof(TradingPilotDbContext))]
    [Migration("20260328221900_DayTradingSchema")]
    partial class DayTradingSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.PostgreSql)
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TradingPilot.Symbols.BrokerSymbolMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BrokerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BrokerSymbolId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SymbolId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("BrokerName", "BrokerSymbolId")
                        .HasDatabaseName("IX_BrokerSymbolMappings_Broker_BrokerId");

                    b.HasIndex("SymbolId", "BrokerName")
                        .IsUnique()
                        .HasDatabaseName("IX_BrokerSymbolMappings_Symbol_Broker");

                    b.ToTable("BrokerSymbolMappings", (string)null);
                });

            modelBuilder.Entity("TradingPilot.Symbols.Symbol", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<string>("Exchange")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActiveForTrading")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsMarginable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsShortable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsWatched")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Sector")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte>("SecurityType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)1);

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)1);

                    b.Property<int?>("WebullExchangeId")
                        .HasColumnType("integer");

                    b.Property<long>("WebullTickerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IsWatched")
                        .HasDatabaseName("IX_Symbols_IsWatched")
                        .HasFilter("\"IsWatched\" = true");

                    b.HasIndex("WebullTickerId")
                        .IsUnique()
                        .HasDatabaseName("IX_Symbols_WebullTickerId");

                    b.ToTable("Symbols", (string)null);
                });

            modelBuilder.Entity("TradingPilot.Symbols.SymbolBar", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ChangeRatio")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)");

                    b.Property<decimal>("Close")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("High")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("Low")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("Open")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<string>("SymbolId")
                        .IsRequired()
                        .HasColumnType("character varying(10)");

                    b.Property<byte>("Timeframe")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Vwap")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp", "Timeframe")
                        .HasDatabaseName("IX_SymbolBars_Timestamp_Timeframe");

                    b.HasIndex("SymbolId", "Timeframe", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("IX_SymbolBars_SymbolId_Timeframe_Timestamp");

                    b.ToTable("SymbolBars", (string)null);
                });

            modelBuilder.Entity("TradingPilot.Symbols.SymbolBookSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string>("AskPrices")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<string>("AskSizes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<string>("BidPrices")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<string>("BidSizes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Depth")
                        .HasColumnType("integer");

                    b.Property<decimal>("Imbalance")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)");

                    b.Property<decimal>("MidPrice")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("Spread")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<string>("SymbolId")
                        .IsRequired()
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_SymbolBookSnapshots_Timestamp");

                    b.HasIndex("SymbolId", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("IX_SymbolBookSnapshots_SymbolId_Timestamp");

                    b.ToTable("SymbolBookSnapshots", (string)null);
                });

            modelBuilder.Entity("TradingPilot.Symbols.SymbolCapitalFlow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("LargeInflow")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("LargeOutflow")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("MediumInflow")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("MediumOutflow")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("SmallInflow")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("SmallOutflow")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("SuperLargeInflow")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("SuperLargeOutflow")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("SymbolId")
                        .IsRequired()
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("SymbolId", "Date")
                        .IsUnique()
                        .HasDatabaseName("IX_SymbolCapitalFlows_SymbolId_Date");

                    b.ToTable("SymbolCapitalFlows", (string)null);
                });

            modelBuilder.Entity("TradingPilot.Symbols.SymbolFinancialSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AvgVolume")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("Beta")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal?>("DividendYield")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal?>("Eps")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal?>("EstEps")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal?>("ForwardPe")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal?>("High52w")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal?>("Low52w")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal?>("MarketCap")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("NextEarningsDate")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("Pe")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<string>("RawJson")
                        .HasColumnType("jsonb");

                    b.Property<decimal?>("ShortFloat")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<string>("SymbolId")
                        .IsRequired()
                        .HasColumnType("character varying(10)");

                    b.Property<decimal?>("Volume")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SymbolId", "Date")
                        .IsUnique()
                        .HasDatabaseName("IX_SymbolFinancialSnapshots_SymbolId_Date");

                    b.ToTable("SymbolFinancialSnapshots", (string)null);
                });

            modelBuilder.Entity("TradingPilot.Symbols.SymbolNews", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CatalystType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ScoredAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SentimentMethod")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("SentimentScore")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)");

                    b.Property<string>("SourceName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("SymbolId")
                        .IsRequired()
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("WebullNewsId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SymbolId", "PublishedAt")
                        .HasDatabaseName("IX_SymbolNews_SymbolId_PublishedAt");

                    b.HasIndex("SymbolId", "WebullNewsId")
                        .IsUnique()
                        .HasDatabaseName("IX_SymbolNews_SymbolId_WebullNewsId");

                    b.ToTable("SymbolNews", (string)null);
                });

            modelBuilder.Entity("TradingPilot.Trading.BarSetup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Atr14")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal>("Atr14_5m")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal?>("CapitalFlowScore")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)");

                    b.Property<string>("CatalystType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte>("Direction")
                        .HasColumnType("smallint");

                    b.Property<decimal>("Ema20")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("Ema20_15m")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("Ema20_5m")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("Ema50_15m")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("Ema50_5m")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("Ema9")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("EntryZoneHigh")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("EntryZoneLow")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("HasCatalyst")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MaxAdverse")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal?>("MaxFavorable")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<int>("NewsCount2Hr")
                        .HasColumnType("integer");

                    b.Property<decimal?>("NewsSentiment")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal?>("PriceAfter1Hr")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal?>("PriceAfter2Hr")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal?>("PriceAfter4Hr")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("Rsi14")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("Rsi14_15m")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("Rsi14_5m")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<byte>("SetupType")
                        .HasColumnType("smallint");

                    b.Property<decimal>("StopLevel")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("Strength")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)");

                    b.Property<string>("SymbolId")
                        .IsRequired()
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("TargetLevel")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<long>("TickerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TrendDirection")
                        .HasColumnType("integer");

                    b.Property<int>("TrendDirection_15m")
                        .HasColumnType("integer");

                    b.Property<int>("TrendDirection_5m")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("VolumeRatio")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("Vwap")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<bool?>("WasCorrect1Hr")
                        .HasColumnType("boolean");

                    b.Property<bool?>("WasCorrect2Hr")
                        .HasColumnType("boolean");

                    b.Property<bool?>("WasCorrect4Hr")
                        .HasColumnType("boolean");

                    b.Property<bool?>("WasTradeable")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("SetupType", "Direction")
                        .HasDatabaseName("IX_BarSetups_SetupType_Direction");

                    b.HasIndex("SymbolId", "Timestamp")
                        .HasDatabaseName("IX_BarSetups_SymbolId_Timestamp");

                    b.ToTable("BarSetups", (string)null);
                });

            modelBuilder.Entity("TradingPilot.Trading.CompletedTrade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<byte?>("DayTradeSetupType")
                        .HasColumnType("smallint");

                    b.Property<byte?>("DayTradeSource")
                        .HasColumnType("smallint");

                    b.Property<decimal>("EntryPrice")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("EntryScore")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)");

                    b.Property<string>("EntrySource")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("ExitPrice")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<string>("ExitReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("ExitTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("HoldSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("IsLong")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Pnl")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<bool?>("SetupInvalidated")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("SetupScore")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)");

                    b.Property<decimal?>("StopDistance")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("TickerId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("TimingScore")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)");

                    b.HasKey("Id");

                    b.HasIndex("ExitTime")
                        .HasDatabaseName("IX_CompletedTrades_ExitTime");

                    b.HasIndex("Ticker", "ExitTime")
                        .HasDatabaseName("IX_CompletedTrades_Ticker_ExitTime");

                    b.ToTable("CompletedTrades", (string)null);
                });

            modelBuilder.Entity("TradingPilot.Trading.DailyWatchlist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Selections")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique()
                        .HasDatabaseName("IX_DailyWatchlists_Date");

                    b.ToTable("DailyWatchlists", (string)null);
                });

            modelBuilder.Entity("TradingPilot.Trading.TradingSignalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AskLevels")
                        .HasColumnType("integer");

                    b.Property<decimal>("AskSweepCost")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AskWallSize")
                        .HasColumnType("numeric");

                    b.Property<int>("BidLevels")
                        .HasColumnType("integer");

                    b.Property<decimal>("BidSweepCost")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BidWallSize")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BookDepthRatio")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CapitalFlowScore")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)");

                    b.Property<decimal?>("ContextScore")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)");

                    b.Property<decimal>("Ema20")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Ema20_15m")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal?>("Ema20_5m")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal?>("Ema50")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal?>("Ema50_15m")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal?>("Ema50_5m")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("Ema9")
                        .HasColumnType("numeric");

                    b.Property<bool?>("HasCatalyst")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Imbalance")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)");

                    b.Property<decimal>("ImbalanceVelocity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LargeOrderSignal")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)");

                    b.Property<int?>("NewsCount2Hr")
                        .HasColumnType("integer");

                    b.Property<decimal?>("NewsSentiment")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)");

                    b.Property<decimal>("ObiSmoothed")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)");

                    b.Property<decimal>("PressureRoc")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal?>("PriceAfter15Min")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal?>("PriceAfter1Hr")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal?>("PriceAfter1Min")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal?>("PriceAfter2Hr")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal?>("PriceAfter30Min")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal?>("PriceAfter4Hr")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal?>("PriceAfter5Min")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("RelativeVolume")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("Rsi14")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Rsi14_15m")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal?>("Rsi14_5m")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("Score")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)");

                    b.Property<decimal?>("SetupScore")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)");

                    b.Property<string>("SignalCatalystType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte?>("SignalSetupType")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Source")
                        .HasColumnType("smallint");

                    b.Property<decimal>("Spread")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal>("SpreadPercentile")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SpreadSignal")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)");

                    b.Property<byte>("Strength")
                        .HasColumnType("smallint");

                    b.Property<string>("SymbolId")
                        .IsRequired()
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("TickMomentum")
                        .HasColumnType("numeric");

                    b.Property<long>("TickerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("TimingScore")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)");

                    b.Property<int?>("TrendDirection_15m")
                        .HasColumnType("integer");

                    b.Property<int?>("TrendDirection_5m")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TrendStrength")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)");

                    b.Property<byte>("Type")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("VolumeRatio")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Vwap")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VwapDeviation")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)");

                    b.Property<bool?>("WasCorrect15Min")
                        .HasColumnType("boolean");

                    b.Property<bool?>("WasCorrect1Hr")
                        .HasColumnType("boolean");

                    b.Property<bool?>("WasCorrect1Min")
                        .HasColumnType("boolean");

                    b.Property<bool?>("WasCorrect2Hr")
                        .HasColumnType("boolean");

                    b.Property<bool?>("WasCorrect30Min")
                        .HasColumnType("boolean");

                    b.Property<bool?>("WasCorrect4Hr")
                        .HasColumnType("boolean");

                    b.Property<bool?>("WasCorrect5Min")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Wobi")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_TradingSignals_Timestamp");

                    b.HasIndex("VerifiedAt")
                        .HasDatabaseName("IX_TradingSignals_VerifiedAt");

                    b.HasIndex("SymbolId", "Timestamp")
                        .HasDatabaseName("IX_TradingSignals_SymbolId_Timestamp");

                    b.HasIndex("Type", "Strength", "Timestamp")
                        .HasDatabaseName("IX_TradingSignals_Type_Strength_Timestamp");

                    b.ToTable("TradingSignals", (string)null);
                });

            modelBuilder.Entity("TradingPilot.Symbols.BrokerSymbolMapping", b =>
                {
                    b.HasOne("TradingPilot.Symbols.Symbol", null)
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TradingPilot.Symbols.SymbolBar", b =>
                {
                    b.HasOne("TradingPilot.Symbols.Symbol", null)
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TradingPilot.Symbols.SymbolBookSnapshot", b =>
                {
                    b.HasOne("TradingPilot.Symbols.Symbol", null)
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TradingPilot.Symbols.SymbolCapitalFlow", b =>
                {
                    b.HasOne("TradingPilot.Symbols.Symbol", null)
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TradingPilot.Symbols.SymbolFinancialSnapshot", b =>
                {
                    b.HasOne("TradingPilot.Symbols.Symbol", null)
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TradingPilot.Symbols.SymbolNews", b =>
                {
                    b.HasOne("TradingPilot.Symbols.Symbol", null)
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TradingPilot.Trading.BarSetup", b =>
                {
                    b.HasOne("TradingPilot.Symbols.Symbol", null)
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TradingPilot.Trading.TradingSignalRecord", b =>
                {
                    b.HasOne("TradingPilot.Symbols.Symbol", null)
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
