// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TradingPilot.EntityFrameworkCore;
using Volo.Abp.EntityFrameworkCore;

#nullable disable

namespace TradingPilot.Migrations
{
    [DbContext(typeof(TradingPilotDbContext))]
    [Migration("20260316183918_AddPaperTradesTable")]
    partial class AddPaperTradesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.PostgreSql)
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TradingPilot.Symbols.Symbol", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<string>("Exchange")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsMarginable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsShortable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsWatched")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateOnly?>("ListDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Sector")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte>("SecurityType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)1);

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)1);

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("WebullExchangeId")
                        .HasColumnType("integer");

                    b.Property<long>("WebullTickerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IsWatched")
                        .HasDatabaseName("IX_Symbols_IsWatched")
                        .HasFilter("\"IsWatched\" = true");

                    b.HasIndex("Ticker")
                        .IsUnique()
                        .HasDatabaseName("IX_Symbols_Ticker");

                    b.HasIndex("WebullTickerId")
                        .IsUnique()
                        .HasDatabaseName("IX_Symbols_WebullTickerId");

                    b.ToTable("Symbols", (string)null);
                });

            modelBuilder.Entity("TradingPilot.Symbols.SymbolBar", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ChangeRatio")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)");

                    b.Property<decimal>("Close")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("High")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("Low")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("Open")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<Guid>("SymbolId")
                        .HasColumnType("uuid");

                    b.Property<byte>("Timeframe")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Vwap")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp", "Timeframe")
                        .HasDatabaseName("IX_SymbolBars_Timestamp_Timeframe");

                    b.HasIndex("SymbolId", "Timeframe", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("IX_SymbolBars_SymbolId_Timeframe_Timestamp");

                    b.ToTable("SymbolBars", (string)null);
                });

            modelBuilder.Entity("TradingPilot.Symbols.SymbolBookSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string>("AskPrices")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<string>("AskSizes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<string>("BidPrices")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<string>("BidSizes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Depth")
                        .HasColumnType("integer");

                    b.Property<decimal>("Imbalance")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)");

                    b.Property<decimal>("MidPrice")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("Spread")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<Guid>("SymbolId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_SymbolBookSnapshots_Timestamp");

                    b.HasIndex("SymbolId", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("IX_SymbolBookSnapshots_SymbolId_Timestamp");

                    b.ToTable("SymbolBookSnapshots", (string)null);
                });

            modelBuilder.Entity("TradingPilot.Symbols.SymbolCapitalFlow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("LargeInflow")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("LargeOutflow")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("MediumInflow")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("MediumOutflow")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("SmallInflow")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("SmallOutflow")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("SuperLargeInflow")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("SuperLargeOutflow")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("SymbolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SymbolId", "Date")
                        .IsUnique()
                        .HasDatabaseName("IX_SymbolCapitalFlows_SymbolId_Date");

                    b.ToTable("SymbolCapitalFlows", (string)null);
                });

            modelBuilder.Entity("TradingPilot.Symbols.SymbolFinancialSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AvgVolume")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("Beta")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal?>("DividendYield")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal?>("Eps")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal?>("EstEps")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal?>("ForwardPe")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal?>("High52w")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal?>("Low52w")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal?>("MarketCap")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("NextEarningsDate")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("Pe")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<string>("RawJson")
                        .HasColumnType("jsonb");

                    b.Property<decimal?>("ShortFloat")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<Guid>("SymbolId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Volume")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SymbolId", "Date")
                        .IsUnique()
                        .HasDatabaseName("IX_SymbolFinancialSnapshots_SymbolId_Date");

                    b.ToTable("SymbolFinancialSnapshots", (string)null);
                });

            modelBuilder.Entity("TradingPilot.Symbols.SymbolNews", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SourceName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("SymbolId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("WebullNewsId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SymbolId", "PublishedAt")
                        .HasDatabaseName("IX_SymbolNews_SymbolId_PublishedAt");

                    b.HasIndex("SymbolId", "WebullNewsId")
                        .IsUnique()
                        .HasDatabaseName("IX_SymbolNews_SymbolId_WebullNewsId");

                    b.ToTable("SymbolNews", (string)null);
                });

            modelBuilder.Entity("TradingPilot.Trading.PaperTrade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal?>("FilledPrice")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<string>("OrderStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Score")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)");

                    b.Property<Guid?>("SignalId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SignalPrice")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<Guid>("SymbolId")
                        .HasColumnType("uuid");

                    b.Property<long>("TickerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("WebullOrderId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_PaperTrades_Timestamp");

                    b.HasIndex("WebullOrderId")
                        .HasDatabaseName("IX_PaperTrades_WebullOrderId");

                    b.HasIndex("SymbolId", "Timestamp")
                        .HasDatabaseName("IX_PaperTrades_SymbolId_Timestamp");

                    b.ToTable("PaperTrades", (string)null);
                });

            modelBuilder.Entity("TradingPilot.Trading.TradingSignalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AskLevels")
                        .HasColumnType("integer");

                    b.Property<int>("BidLevels")
                        .HasColumnType("integer");

                    b.Property<decimal>("Imbalance")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)");

                    b.Property<decimal>("LargeOrderSignal")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)");

                    b.Property<decimal>("ObiSmoothed")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)");

                    b.Property<decimal>("PressureRoc")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal?>("PriceAfter15Min")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal?>("PriceAfter1Min")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal?>("PriceAfter30Min")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal?>("PriceAfter5Min")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Score")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)");

                    b.Property<decimal>("Spread")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal>("SpreadSignal")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)");

                    b.Property<byte>("Strength")
                        .HasColumnType("smallint");

                    b.Property<Guid>("SymbolId")
                        .HasColumnType("uuid");

                    b.Property<long>("TickerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("Type")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("WasCorrect15Min")
                        .HasColumnType("boolean");

                    b.Property<bool?>("WasCorrect1Min")
                        .HasColumnType("boolean");

                    b.Property<bool?>("WasCorrect30Min")
                        .HasColumnType("boolean");

                    b.Property<bool?>("WasCorrect5Min")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Wobi")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_TradingSignals_Timestamp");

                    b.HasIndex("VerifiedAt")
                        .HasDatabaseName("IX_TradingSignals_VerifiedAt");

                    b.HasIndex("SymbolId", "Timestamp")
                        .HasDatabaseName("IX_TradingSignals_SymbolId_Timestamp");

                    b.HasIndex("Type", "Strength", "Timestamp")
                        .HasDatabaseName("IX_TradingSignals_Type_Strength_Timestamp");

                    b.ToTable("TradingSignals", (string)null);
                });

            modelBuilder.Entity("TradingPilot.Symbols.SymbolBar", b =>
                {
                    b.HasOne("TradingPilot.Symbols.Symbol", null)
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TradingPilot.Symbols.SymbolBookSnapshot", b =>
                {
                    b.HasOne("TradingPilot.Symbols.Symbol", null)
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TradingPilot.Symbols.SymbolCapitalFlow", b =>
                {
                    b.HasOne("TradingPilot.Symbols.Symbol", null)
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TradingPilot.Symbols.SymbolFinancialSnapshot", b =>
                {
                    b.HasOne("TradingPilot.Symbols.Symbol", null)
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TradingPilot.Symbols.SymbolNews", b =>
                {
                    b.HasOne("TradingPilot.Symbols.Symbol", null)
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TradingPilot.Trading.PaperTrade", b =>
                {
                    b.HasOne("TradingPilot.Symbols.Symbol", null)
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TradingPilot.Trading.TradingSignalRecord", b =>
                {
                    b.HasOne("TradingPilot.Symbols.Symbol", null)
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
